# Path to your oh-my-zsh installation.
export ZSH="$HOME/.oh-my-zsh"

# Set name of the theme to load.
ZSH_THEME="robbyrussell"

# Enable Correction
ENABLE_CORRECTION="true"

# Completion waiting dots
COMPLETION_WAITING_DOTS="%F{yellow}waiting...%f"

# User configuration
source $ZSH/oh-my-zsh.sh

autoload -U compinit; compinit

[[ -f ~/.aliases ]] && source ~/.aliases

source $HOMEBREW_PREFIX/share/zsh-autosuggestions/zsh-autosuggestions.zsh

export ZSH_HIGHLIGHT_HIGHLIGHTERS_DIR=$HOMEBREW_PREFIX/share/zsh-syntax-highlighting/highlighters
source $HOMEBREW_PREFIX/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh

# Plugins
plugins=(
  git
  zsh-autosuggestions
  zsh-syntax-highlighting
)

### Added by bootstrap.sh ###
