tap "dracula/install"
tap "homebrew/bundle"
tap "homebrew/cask-fonts"
tap "homebrew/cask-versions"
tap "homebrew/cask"
tap "homebrew/core"
tap "homebrew/services"

# brew "aws-cdk"
# brew "autoconf"
# brew "automake"
# brew "bash"
# brew "binutils"
# brew "cmake"
# brew "coreutils"
# brew "ctop"
# brew "curl"
# brew "findutils"
# brew "gawk"
# brew "gcc"
# brew "gh"
# brew "git-lfs"
# brew "git-secrets"
# brew "git"
# brew "gmp"
# brew "gnu-getopt"
# brew "gnu-indent"
# brew "gnu-sed"
# brew "gnu-tar"
# brew "gnu-which"
# brew "gnutls"
# brew "go"
# brew "go@1.19"
# brew "grep"
# brew "htop"
# brew "hugo"
# brew "icu4c"
# brew "jq"
# brew "kind"
# brew "kotlin"
# brew "libtool"
# brew "libuv"
brew "mas"
# brew "mercurial"
# brew "mono-libgdiplus"
# brew "moreutils"
# brew "ncurses"
# brew "netcdf"
# brew "nmap"
# brew "node"
# brew "nvm"
# brew "gimme-aws-creds"
# brew "openjdk"
# brew "openssh"
# brew "openssl"
# brew "p7zip"
# brew "pandoc"
# brew "pidof"
# brew "pkg-config"
# brew "pstree"
# brew "python"
# brew "python@3.11"
# brew "rbenv"
# brew "rename"
# brew "rsync"
# brew "ruby"
# brew "screen"
# brew "sphinx-doc"
# brew "ssh-copy-id"
# brew "terminal-notifier"
# brew "terraform"
# brew "tree"
# brew "vim"
# brew "wget"
# brew "xz"
# brew "yarn"
# brew "ksh93"
# brew "oksh"
# brew "zsh-syntax-highlighting"
# brew "scorecard"
# brew "typescript"
# brew "jinja2-cli"
# brew "awscli"
# brew "kubernetes-cli"
# brew "nano"
# brew "nanorc"
# brew "minikube"
# brew "helm"
#
#
# cask "1password"
# cask "1password-cli"
# cask "docker"
# cask "dotnet-sdk"
# cask "dracula-gitkraken"
# cask "dracula-terminal"
# cask "firefox"
# cask "gitkraken"
# cask "google-chrome"
# cask "iterm2"
# cask "jetbrains-toolbox"
# cask "kaleidoscope"
# cask "oracle-jdk"
# cask "postman"
# cask "visual-studio-code"
# cask "powershell"
# cask "font-source-code-pro"
# cask "font-ibm-plex"
# cask "font-consolas-for-powerline"
# cask "font-anonymice-powerline"

# 1482454543  Twitter                        (9.30)
# 506189836   Harvest                        (2.3.2)
# 402476602   Sketch                         (2.4.4)
# 1462114288  Grammarly for Safari           (9.67)
# 1153157709  Speedtest                      (1.27)
# 409907375   Remote Desktop                 (3.9.6)
# 1176895641  Spark                          (2.11.30)
# 1496543317  Book Tracker                   (3.1.13)
# 524373870   Due                            (23.4)
# 889428659   xScope                         (4.6)
# 1147396723  WhatsApp                       (2.2332.15)
# 803453959   Slack                          (4.33.84)
# 419330170   Moom                           (3.2.25)
# 640199958   Developer                      (10.4.1)
# 1454139710  Hyperspace Desktop             (1.1.4)
# 1274495053  Microsoft To Do                (2.102)
# 490152466   iBooks Author                  (2.6.1)
# 1482630322  Internet Access Policy Viewer  (1.0)
# 408981434   iMovie                         (10.3.8)
# 1324203419  Ground News                    (3.0.3)
# 1569813296  1Password for Safari           (2.13.0)
# 1480068668  Messenger                      (192.0)
# 451640037   Classic Color Meter            (2.1.1)
# 1316083518  FUJIFILM Prints & Gifts        (1.7.1)
# 1450757574  Mastonaut                      (1.3.9)
# 403095673   Fontcase                       (2.1.8)
# 1295203466  Microsoft Remote Desktop       (10.8.4)
# 437835477   Page Layers                    (1.9.10)
# 497799835   Xcode                          (14.3.1)
# 470158793   Keka                           (1.3.2)
# 1594183810  Shortery                       (4.2)
# 775737590   iA Writer                      (6.0.11)
# 1209754386  eDrawings                      (31.3.0040)
# 1460330618  Hype 4                         (4.1.13)
# 1230249825  VMware Remote Console          (12.0.4)
# 405399194   Kindle                         (1.40.1)
# 463541543   Gemini                         (1.5.17)
# 409201541   Pages                          (13.1)
# 409203825   Numbers                        (13.1)
# 425424353   The Unarchiver                 (4.3.5)
# 955981476   SimCity™: Complete Edition     (1.0.4)
# 1006087419  SnippetsLab                    (2.3)
# 882637653   Debit & Credit                 (6.1.5)
# 1224268771  Screens                        (4.12.11)
# 1475924331  RealtimeBART                   (1.0)
# 823766827   OneDrive                       (23.147.0716)
# 409183694   Keynote                        (13.1)
# 675649574   NetAdmin Pro                   (2.0.14)
# 1181028777  FlipClock                      (5.20)
# 1312926037  stoic.                         (2023.32)
# 403304796   iNet Network Scanner           (3.0.1)
# 1431995750  Taskheat                       (1.8.15)
# 475193367   Synalyze It! Pro               (1.32)
# 494803304   WiFi Explorer                  (3.4.4)

# 462054704  Microsoft Word                 (16.75)
# 784801555  Microsoft OneNote              (16.75)
# 985367838  Microsoft Outlook              (16.75.1)
# 462058435  Microsoft Excel                (16.75.2)
# 462062816  Microsoft PowerPoint           (16.75)
# 1295203466  Microsoft Remote Desktop       (10.8.4)

mas "Xcode", id: 497799835
mas "1Password", id: 443987910
mas "iA Writer", id: 775737590
mas "Slack", id: 803453959
mas "Remote Desktop", id: 409907375
mas "Microsoft Remote Desktop", id: 1295203466
mas "Microsoft Word", id: 462054704
mas "Microsoft Excel", id: 462058435
mas "Microsoft PowerPoint", id: 462062816
mas "Microsoft Outlook", id: 985367838
mas "Microsoft OneNote", id: 784801555
mas "Microsoft To Do", id: 1274495053

# mas "WhatsApp", id: 1147396723
# mas "Speedtest", id: 1153157709
# mas "Spark", id: 1176895641
