mas "Microsoft Word", id: 462054704
mas "Microsoft Excel", id: 462058435
mas "Microsoft PowerPoint", id: 462062816
mas "Microsoft Outlook", id: 985367838
mas "Microsoft OneNote", id: 784801555
mas "Microsoft To Do", id: 1274495053